In [25]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
#database connection settings
import psycopg2

db_name = "traviato_development"
db_host = "localhost"
db_port = "5432"
db_user = "lievgarcia"
db_pwd = "traviato81"

conn = psycopg2.connect(database=db_name, user=db_user, password=db_pwd, host=db_host, port=db_port)

In [58]:
import pandas as pd
import numpy as np

cursor = conn.cursor()

album_info_df = pd.read_csv('../../data/raw/streaming/dzr_albums.csv', index_col=0)
album_info_df = album_info_df.replace({r'\r\n': ''}, regex=True)

# album_info_df['composer'].str.strip(r'\\n')
# album_info_df['c'] = album_info_df.apply(lambda row: row['composer'].replace('\n', ''), index=1)

album_df = pd.read_csv('../../data/raw/streaming/dzr_isrc_song.csv', names=['album_id', 'song_isrc', 'song_id'])
song_df = pd.read_csv('../../data/raw/streaming/dzr_songs_isrc_listened.csv', names=['song_isrc', 'times_played'])

df = album_df.merge(album_info_df, left_on='album_id', right_on='deezer_id', how='outer')
df = df.merge(song_df, left_on='song_isrc', right_on='song_isrc', how='outer')

#Fill blank plays
df[['times_played']] = df[['times_played']].fillna(value=0)

# print(df.head())

o_df = df.groupby(['album_id'])
o_df = o_df.agg({'times_played': np.sum })
o_df = o_df.sort_values(by=['times_played'], ascending=False)
print(o_df.shape)
o_df.head(100)

(11734, 1)

          times_played
album_id
15194141      278050.0
1499391       253380.0
1234480       172350.0
4069521       168986.0
6410727       105944.0
4069701       105336.0
6023836       104286.0
7816316        98613.0
7423383        81976.0
4069581        74814.0
4071881        71241.0
1232970        69559.0
5954044        68787.0
5909671        67277.0
1233020        66386.0
3742221        64710.0
529360         64710.0
2734981        51773.0
4069951        48034.0
309280         48034.0
15770666       45270.0
7065483        44494.0
8996441        41227.0
14400498       41227.0
4068971        40858.0
4071541        40858.0
6244959        40296.0
7915850        39458.0
7738423        39458.0
6136727        37808.0
...                ...
46582032       21048.0
4071731        20890.0
72891          20590.0
1125199        19744.0
49985552       19280.0
393628         18750.0
1467521        18424.0
13989800       18368.0
7524405        18199.0
4015681        18190.0
1685501        18059.0
307336         17883.0
4071951        17883.0
3742571        17837.0
49386232       17833.0
4068701        17832.0
4071371        17832.0
49067212       17813.0
3491531        17745.0
398698         17553.0
4069821        17297.0
1134421        17297.0
6318779        17297.0
309177         17224.0
472827         16943.0
7738411        16488.0
366400         16260.0
6000855        16104.0
359901         16104.0
6598022        15647.0

[100 rows x 1 columns]

In [51]:
# album_info_df.head()